version: 0.2

env:
  variables:
    S3_BUCKET: code-bachlmayr
    PACKAGE: "github.com/gezza-b/fetchgo"

phases:
  install:
    commands:
      - echo starting the install phase 

      # copy application source code into that directory structure.
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}" 
      
      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

    finally:
      - echo end of install phase
      
  pre_build: 
    commands:
      - echo starting the pre-build phase
      # Make sure we're in the project directory within our GOPATH

      - cd "/go/src/${PACKAGE}"

      # Fetch all dependencies
      - go get -t ./...

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      #- docker login -u AWS --password-stdin -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
    finally:
      - echo end of pre-build phase

  build:
    commands:
      - echo starting the build phase
      # Build application
      - cd "/go/src/${PACKAGE}"

      #- go build -a src/fetch.go
      - go build -o marketplace

      # Package our application with AWS SAM
      #- echo start packaging ${S3_BUCKET}
      #- aws cloudformation package --template-file template-lambda.yml --s3-bucket ${S3_BUCKET} --output-template-file s3://code-bachlmayr/packaged.yml
      #- aws cloudformation package --template-file template-sam.yml --s3-bucket ${S3_BUCKET} --output-template-file s3://code-bachlmayr/packaged.yml
     
      # copy CFN template
      #- echo start copying ${CODEBUILD_SRC_DIR}/template-lambda.yml
      #- aws s3 cp ${CODEBUILD_SRC_DIR}/template-lambda.yml s3://code-bachlmayr/template-lambda.yml
      
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
    finally:
      - echo end of build phase

  post_build:
    commands:
      - echo starting the post_build phase, but not really

      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - echo writting image definitions file

      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      
      
    finally:
      - echo end of post_build phase
artifacts:
    files: imagedefinitions.json
  
# ArtifactStore: 
#   Type: S3 
#   Location:
#     Ref: $S3_BUCKET 
#   EncryptionKey:
#     Id: $ENCRYPTION_KEY
#     Type: KMS