AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  marketplace
  
  Sample SAM Template for marketplace

Resources:
  marketplace:
    Type: AWS::Serverless::Function
    Properties:      
      Runtime: go1.x
      Handler: main
      Timeout: 10      
      Architectures:
        - x86_64
      Environment:
        Variables:
          DB_HOST: marketplace.ceekdskscr6x.us-east-1.rds.amazonaws.com
          DB_DRIVER: postgres
          DB_USER: userdb
          DB_PASSWORD: pddbmarketplace
          DB_NAME: marketplace
          DB_PORT: 5432
      Events:        
        ProjectHandler:
          Type: Api
          Properties:
            Path: '/projects'
            Method: POST